export { api, ApiError, NetworkError, tokenStore, unwrap, unwrapList, BASE_URL } from './client'
export { authApi } from './authApi'
export { metaApi } from './metaApi'

// Phases 3–4
export { masterApi, organizationApi } from './organizationApi'
export { subscriptionApi } from './subscriptionApi'
export { branchApi } from './branchApi'
export { buildingApi, floorApi, roomApi, bedApi, propertyApi } from './propertyApi'
export { roleApi, permissionApi } from './roleApi'
export { userApi } from './userApi'
export { dashboardApi } from './dashboardApi'

// Phases 5–16
export { residentApi } from './residentApi'
export { invoiceApi } from './invoiceApi'
export { paymentApi } from './paymentApi'
export { rentApi } from './rentApi'
export { attendanceApi } from './attendanceApi'
export { scanApi } from './scanApi'
export { visitorApi } from './visitorApi'
export { gatePassApi } from './gatePassApi'
export { foodApi } from './foodApi'
export { laundryApi } from './laundryApi'
export { complaintApi } from './complaintApi'
export { queryApi } from './queryApi'
export { expenseApi } from './expenseApi'
export { inventoryApi } from './inventoryApi'
export { assetApi } from './assetApi'
export { reportApi } from './reportApi'
export { notificationApi } from './notificationApi'
export { announcementApi } from './announcementApi'
export { settingsApi } from './settingsApi'
export { auditApi } from './auditApi'
export { searchApi } from './searchApi'
export { platformSettingsApi } from './platformSettingsApi'
export { meApi } from './meApi'
