"""property hierarchy and full plan limits

Revision ID: 41ef8f07564e
Revises: 0002_auth_tables
Create Date: 2026-09-08 16:39:59.503538
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0003_property_and_limits'
down_revision: str | None = '0002_auth_tables'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('number_of_floors', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'UNDER_CONSTRUCTION', name='buildingstatus', native_enum=False, length=24), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('number_of_floors > 0', name='ck_buildings_floors_positive'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'code', name='uq_buildings_branch_code')
    )
    op.create_index(op.f('ix_buildings_branch_id'), 'buildings', ['branch_id'], unique=False)
    op.create_index('ix_buildings_org_branch', 'buildings', ['organization_id', 'branch_id'], unique=False)
    op.create_index(op.f('ix_buildings_organization_id'), 'buildings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_buildings_status'), 'buildings', ['status'], unique=False)
    op.create_table('floors',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('building_id', sa.UUID(), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='floorstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'floor_number', name='uq_floors_building_number')
    )
    op.create_index(op.f('ix_floors_branch_id'), 'floors', ['branch_id'], unique=False)
    op.create_index(op.f('ix_floors_building_id'), 'floors', ['building_id'], unique=False)
    op.create_index('ix_floors_org_branch', 'floors', ['organization_id', 'branch_id'], unique=False)
    op.create_index(op.f('ix_floors_organization_id'), 'floors', ['organization_id'], unique=False)
    op.create_index(op.f('ix_floors_status'), 'floors', ['status'], unique=False)
    op.create_table('rooms',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('building_id', sa.UUID(), nullable=False),
    sa.Column('floor_id', sa.UUID(), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('room_type', sa.String(length=40), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('gender_policy', sa.Enum('MALE', 'FEMALE', 'ANY', name='genderpolicy', native_enum=False, length=10), nullable=False),
    sa.Column('rent_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deposit_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('has_ac', sa.Boolean(), nullable=False),
    sa.Column('has_attached_bathroom', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', name='roomstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity > 0', name='ck_rooms_capacity_positive'),
    sa.CheckConstraint('rent_amount >= 0 AND deposit_amount >= 0', name='ck_rooms_money_non_negative'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('floor_id', 'room_number', name='uq_rooms_floor_number')
    )
    op.create_index(op.f('ix_rooms_branch_id'), 'rooms', ['branch_id'], unique=False)
    op.create_index(op.f('ix_rooms_floor_id'), 'rooms', ['floor_id'], unique=False)
    op.create_index('ix_rooms_org_branch', 'rooms', ['organization_id', 'branch_id'], unique=False)
    op.create_index(op.f('ix_rooms_organization_id'), 'rooms', ['organization_id'], unique=False)
    op.create_index(op.f('ix_rooms_status'), 'rooms', ['status'], unique=False)
    op.create_table('beds',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('bed_number', sa.String(length=10), nullable=False),
    sa.Column('bed_code', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'RESERVED', 'OCCUPIED', 'MAINTENANCE', 'BLOCKED', name='bedstatus', native_enum=False, length=20), nullable=False),
    sa.Column('rent_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('current_customer_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'OCCUPIED' AND current_customer_id IS NOT NULL) OR (status <> 'OCCUPIED' AND current_customer_id IS NULL)", name='ck_beds_occupancy_consistent'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'bed_number', name='uq_beds_room_number')
    )
    op.create_index(op.f('ix_beds_bed_code'), 'beds', ['bed_code'], unique=False)
    op.create_index(op.f('ix_beds_branch_id'), 'beds', ['branch_id'], unique=False)
    op.create_index(op.f('ix_beds_current_customer_id'), 'beds', ['current_customer_id'], unique=False)
    op.create_index('ix_beds_org_branch_status', 'beds', ['organization_id', 'branch_id', 'status'], unique=False)
    op.create_index(op.f('ix_beds_organization_id'), 'beds', ['organization_id'], unique=False)
    op.create_index(op.f('ix_beds_room_id'), 'beds', ['room_id'], unique=False)
    op.create_index(op.f('ix_beds_status'), 'beds', ['status'], unique=False)
    op.add_column('organizations', sa.Column('notes', sa.String(length=1000), nullable=True))
    op.add_column('subscription_plans', sa.Column('max_buildings', sa.Integer(), nullable=False, server_default='2'))
    op.add_column('subscription_plans', sa.Column('max_floors', sa.Integer(), nullable=False, server_default='8'))
    op.add_column('subscription_plans', sa.Column('max_rooms', sa.Integer(), nullable=False, server_default='25'))
    op.add_column('subscription_plans', sa.Column('max_admins', sa.Integer(), nullable=False, server_default='2'))
    op.add_column('subscription_plans', sa.Column('monthly_transaction_limit', sa.Integer(), nullable=False, server_default='500'))
    op.add_column('subscriptions', sa.Column('max_buildings', sa.Integer(), nullable=True))
    op.add_column('subscriptions', sa.Column('max_floors', sa.Integer(), nullable=True))
    op.add_column('subscriptions', sa.Column('max_rooms', sa.Integer(), nullable=True))
    op.add_column('subscriptions', sa.Column('max_admins', sa.Integer(), nullable=True))
    op.add_column('subscriptions', sa.Column('monthly_transaction_limit', sa.Integer(), nullable=True))
    # The server defaults above exist only to backfill the rows that already
    # existed when this migration ran. The application always supplies a value,
    # so the defaults are dropped again to keep the schema matching the models.
    for column in ("max_buildings", "max_floors", "max_rooms",
                   "max_admins", "monthly_transaction_limit"):
        op.alter_column("subscription_plans", column, server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'monthly_transaction_limit')
    op.drop_column('subscriptions', 'max_admins')
    op.drop_column('subscriptions', 'max_rooms')
    op.drop_column('subscriptions', 'max_floors')
    op.drop_column('subscriptions', 'max_buildings')
    op.drop_column('subscription_plans', 'monthly_transaction_limit')
    op.drop_column('subscription_plans', 'max_admins')
    op.drop_column('subscription_plans', 'max_rooms')
    op.drop_column('subscription_plans', 'max_floors')
    op.drop_column('subscription_plans', 'max_buildings')
    op.drop_column('organizations', 'notes')
    op.drop_index(op.f('ix_beds_status'), table_name='beds')
    op.drop_index(op.f('ix_beds_room_id'), table_name='beds')
    op.drop_index(op.f('ix_beds_organization_id'), table_name='beds')
    op.drop_index('ix_beds_org_branch_status', table_name='beds')
    op.drop_index(op.f('ix_beds_current_customer_id'), table_name='beds')
    op.drop_index(op.f('ix_beds_branch_id'), table_name='beds')
    op.drop_index(op.f('ix_beds_bed_code'), table_name='beds')
    op.drop_table('beds')
    op.drop_index(op.f('ix_rooms_status'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_organization_id'), table_name='rooms')
    op.drop_index('ix_rooms_org_branch', table_name='rooms')
    op.drop_index(op.f('ix_rooms_floor_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_branch_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_floors_status'), table_name='floors')
    op.drop_index(op.f('ix_floors_organization_id'), table_name='floors')
    op.drop_index('ix_floors_org_branch', table_name='floors')
    op.drop_index(op.f('ix_floors_building_id'), table_name='floors')
    op.drop_index(op.f('ix_floors_branch_id'), table_name='floors')
    op.drop_table('floors')
    op.drop_index(op.f('ix_buildings_status'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_organization_id'), table_name='buildings')
    op.drop_index('ix_buildings_org_branch', table_name='buildings')
    op.drop_index(op.f('ix_buildings_branch_id'), table_name='buildings')
    op.drop_table('buildings')
    # ### end Alembic commands ###
