"""operational modules

Revision ID: 87b0153814be
Revises: 0004_enum_checks
Create Date: 2026-09-08 17:50:49.122534
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0005_operational_modules'
down_revision: str | None = '0004_enum_checks'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_settings',
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('timezone', sa.String(length=40), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('rent_due_day', sa.Integer(), nullable=False),
    sa.Column('late_fee_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('late_fee_after_days', sa.Integer(), nullable=False),
    sa.Column('invoice_prefix', sa.String(length=10), nullable=False),
    sa.Column('gate_duplicate_window_seconds', sa.Integer(), nullable=False),
    sa.Column('visitor_approval_required', sa.Boolean(), nullable=False),
    sa.Column('gate_pass_approval_required', sa.Boolean(), nullable=False),
    sa.Column('food_enabled', sa.Boolean(), nullable=False),
    sa.Column('laundry_enabled', sa.Boolean(), nullable=False),
    sa.Column('meal_optout_cutoff_hours', sa.Integer(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rent_due_day BETWEEN 1 AND 28', name='ck_settings_rent_due_day'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', name='uq_settings_org')
    )
    op.create_index(op.f('ix_organization_settings_organization_id'), 'organization_settings', ['organization_id'], unique=False)
    op.create_table('announcements',
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('audience', sa.Enum('ALL', 'RESIDENTS', 'STAFF', 'BRANCH', name='announcementaudience', native_enum=False, length=12), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='ticketpriority', native_enum=False, length=10), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='publishstatus', native_enum=False, length=12), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_audience'), 'announcements', ['audience'], unique=False)
    op.create_index(op.f('ix_announcements_branch_id'), 'announcements', ['branch_id'], unique=False)
    op.create_index(op.f('ix_announcements_organization_id'), 'announcements', ['organization_id'], unique=False)
    op.create_index(op.f('ix_announcements_status'), 'announcements', ['status'], unique=False)
    op.create_table('attendance',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.Enum('RESIDENT', 'STAFF', name='attendancesubject', native_enum=False, length=12), nullable=False),
    sa.Column('resident_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('on_date', sa.Date(), nullable=False),
    sa.Column('check_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', 'ON_LEAVE', name='attendancestatus', native_enum=False, length=12), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(resident_id IS NOT NULL AND user_id IS NULL) OR (resident_id IS NULL AND user_id IS NOT NULL)', name='ck_attendance_one_subject'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resident_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resident_id', 'on_date', name='uq_attendance_resident_day'),
    sa.UniqueConstraint('user_id', 'on_date', name='uq_attendance_user_day')
    )
    op.create_index(op.f('ix_attendance_branch_id'), 'attendance', ['branch_id'], unique=False)
    op.create_index(op.f('ix_attendance_on_date'), 'attendance', ['on_date'], unique=False)
    op.create_index('ix_attendance_org_branch_date', 'attendance', ['organization_id', 'branch_id', 'on_date'], unique=False)
    op.create_index(op.f('ix_attendance_organization_id'), 'attendance', ['organization_id'], unique=False)
    op.create_index(op.f('ix_attendance_resident_id'), 'attendance', ['resident_id'], unique=False)
    op.create_index(op.f('ix_attendance_status'), 'attendance', ['status'], unique=False)
    op.create_index(op.f('ix_attendance_subject'), 'attendance', ['subject'], unique=False)
    op.create_index(op.f('ix_attendance_user_id'), 'attendance', ['user_id'], unique=False)
    op.create_table('expenses',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('expense_number', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('spent_on', sa.Date(), nullable=False),
    sa.Column('vendor', sa.String(length=160), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('attachment_reference', sa.String(length=300), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_expenses_amount_positive'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'expense_number', name='uq_expenses_org_number')
    )
    op.create_index(op.f('ix_expenses_branch_id'), 'expenses', ['branch_id'], unique=False)
    op.create_index(op.f('ix_expenses_category'), 'expenses', ['category'], unique=False)
    op.create_index('ix_expenses_org_branch_date', 'expenses', ['organization_id', 'branch_id', 'spent_on'], unique=False)
    op.create_index(op.f('ix_expenses_organization_id'), 'expenses', ['organization_id'], unique=False)
    op.create_index(op.f('ix_expenses_spent_on'), 'expenses', ['spent_on'], unique=False)
    op.create_table('food_menus',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('on_date', sa.Date(), nullable=False),
    sa.Column('meal', sa.Enum('BREAKFAST', 'LUNCH', 'SNACK', 'DINNER', name='mealtype', native_enum=False, length=12), nullable=False),
    sa.Column('items', sa.Text(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('serve_from', sa.Time(), nullable=True),
    sa.Column('serve_to', sa.Time(), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'on_date', 'meal', name='uq_food_menu_branch_day_meal')
    )
    op.create_index(op.f('ix_food_menus_branch_id'), 'food_menus', ['branch_id'], unique=False)
    op.create_index(op.f('ix_food_menus_meal'), 'food_menus', ['meal'], unique=False)
    op.create_index(op.f('ix_food_menus_on_date'), 'food_menus', ['on_date'], unique=False)
    op.create_index(op.f('ix_food_menus_organization_id'), 'food_menus', ['organization_id'], unique=False)
    op.create_table('gate_passes',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('resident_id', sa.UUID(), nullable=False),
    sa.Column('pass_number', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=True),
    sa.Column('from_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('to_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_emergency', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='gatepassstatus', native_enum=False, length=12), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('to_at > from_at', name='ck_gate_passes_window'),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resident_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'pass_number', name='uq_gate_passes_org_number')
    )
    op.create_index(op.f('ix_gate_passes_branch_id'), 'gate_passes', ['branch_id'], unique=False)
    op.create_index('ix_gate_passes_org_branch_status', 'gate_passes', ['organization_id', 'branch_id', 'status'], unique=False)
    op.create_index(op.f('ix_gate_passes_organization_id'), 'gate_passes', ['organization_id'], unique=False)
    op.create_index(op.f('ix_gate_passes_resident_id'), 'gate_passes', ['resident_id'], unique=False)
    op.create_index(op.f('ix_gate_passes_status'), 'gate_passes', ['status'], unique=False)
    op.create_table('inventory_items',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('minimum_stock', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('supplier', sa.String(length=160), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_inventory_quantity_non_negative'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'sku', name='uq_inventory_branch_sku')
    )
    op.create_index(op.f('ix_inventory_items_branch_id'), 'inventory_items', ['branch_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_category'), 'inventory_items', ['category'], unique=False)
    op.create_index(op.f('ix_inventory_items_name'), 'inventory_items', ['name'], unique=False)
    op.create_index(op.f('ix_inventory_items_organization_id'), 'inventory_items', ['organization_id'], unique=False)
    op.create_table('invoices',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('resident_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=30), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('period', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('late_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'PARTIAL', 'PAID', 'OVERDUE', 'CANCELLED', name='invoicestatus', native_enum=False, length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total >= 0 AND paid_amount >= 0', name='ck_invoices_non_negative'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resident_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'invoice_number', name='uq_invoices_org_number')
    )
    op.create_index(op.f('ix_invoices_branch_id'), 'invoices', ['branch_id'], unique=False)
    op.create_index(op.f('ix_invoices_due_date'), 'invoices', ['due_date'], unique=False)
    op.create_index('ix_invoices_org_branch_status', 'invoices', ['organization_id', 'branch_id', 'status'], unique=False)
    op.create_index(op.f('ix_invoices_organization_id'), 'invoices', ['organization_id'], unique=False)
    op.create_index(op.f('ix_invoices_period'), 'invoices', ['period'], unique=False)
    op.create_index(op.f('ix_invoices_resident_id'), 'invoices', ['resident_id'], unique=False)
    op.create_index('ix_invoices_resident_period', 'invoices', ['resident_id', 'period'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('laundry_slots',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('on_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'FULL', 'CLOSED', 'CANCELLED', name='laundryslotstatus', native_enum=False, length=12), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity > 0', name='ck_laundry_slot_capacity'),
    sa.CheckConstraint('end_time > start_time', name='ck_laundry_slot_window'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'on_date', 'start_time', name='uq_laundry_slot_branch_day_start')
    )
    op.create_index(op.f('ix_laundry_slots_branch_id'), 'laundry_slots', ['branch_id'], unique=False)
    op.create_index(op.f('ix_laundry_slots_on_date'), 'laundry_slots', ['on_date'], unique=False)
    op.create_index(op.f('ix_laundry_slots_organization_id'), 'laundry_slots', ['organization_id'], unique=False)
    op.create_index(op.f('ix_laundry_slots_status'), 'laundry_slots', ['status'], unique=False)
    op.create_table('meal_attendance',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('resident_id', sa.UUID(), nullable=False),
    sa.Column('on_date', sa.Date(), nullable=False),
    sa.Column('meal', sa.Enum('BREAKFAST', 'LUNCH', 'SNACK', 'DINNER', name='mealtype', native_enum=False, length=12), nullable=False),
    sa.Column('status', sa.Enum('EXPECTED', 'ATTENDED', 'SKIPPED', 'OPTED_OUT', name='mealstatus', native_enum=False, length=12), nullable=False),
    sa.Column('marked_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marked_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resident_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resident_id', 'on_date', 'meal', name='uq_meal_resident_day_meal')
    )
    op.create_index(op.f('ix_meal_attendance_branch_id'), 'meal_attendance', ['branch_id'], unique=False)
    op.create_index(op.f('ix_meal_attendance_on_date'), 'meal_attendance', ['on_date'], unique=False)
    op.create_index(op.f('ix_meal_attendance_organization_id'), 'meal_attendance', ['organization_id'], unique=False)
    op.create_index(op.f('ix_meal_attendance_resident_id'), 'meal_attendance', ['resident_id'], unique=False)
    op.create_index(op.f('ix_meal_attendance_status'), 'meal_attendance', ['status'], unique=False)
    op.create_index('ix_meal_org_branch_date', 'meal_attendance', ['organization_id', 'branch_id', 'on_date'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('resident_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('RENT_DUE', 'PAYMENT_RECEIVED', 'PAYMENT_VERIFIED', 'COMPLAINT_UPDATED', 'VISITOR_REQUEST', 'GATE_PASS', 'ANNOUNCEMENT', 'SUBSCRIPTION', 'SYSTEM', name='notificationtype', native_enum=False, length=24), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(user_id IS NOT NULL AND resident_id IS NULL) OR (user_id IS NULL AND resident_id IS NOT NULL)', name='ck_notifications_one_recipient'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resident_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_kind'), 'notifications', ['kind'], unique=False)
    op.create_index(op.f('ix_notifications_organization_id'), 'notifications', ['organization_id'], unique=False)
    op.create_index(op.f('ix_notifications_resident_id'), 'notifications', ['resident_id'], unique=False)
    op.create_index('ix_notifications_resident_read', 'notifications', ['resident_id', 'read_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'read_at'], unique=False)
    op.create_table('resident_kyc',
    sa.Column('resident_id', sa.UUID(), nullable=False),
    sa.Column('id_type', sa.Enum('AADHAAR', 'PAN', 'PASSPORT', 'DRIVING_LICENCE', 'VOTER_ID', 'OTHER', name='kycidtype', native_enum=False, length=20), nullable=False),
    sa.Column('id_number', sa.String(length=80), nullable=False),
    sa.Column('document_reference', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('NOT_SUBMITTED', 'SUBMITTED', 'VERIFIED', 'REJECTED', name='kycstatus', native_enum=False, length=20), nullable=False),
    sa.Column('verified_by_id', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resident_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resident_id', 'id_type', name='uq_resident_kyc_type')
    )
    op.create_index(op.f('ix_resident_kyc_organization_id'), 'resident_kyc', ['organization_id'], unique=False)
    op.create_index(op.f('ix_resident_kyc_resident_id'), 'resident_kyc', ['resident_id'], unique=False)
    op.create_index(op.f('ix_resident_kyc_status'), 'resident_kyc', ['status'], unique=False)
    op.create_table('support_queries',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('resident_id', sa.UUID(), nullable=True),
    sa.Column('ticket_number', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ANSWERED', 'CLOSED', name='querystatus', native_enum=False, length=12), nullable=False),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resident_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'ticket_number', name='uq_queries_org_ticket')
    )
    op.create_index(op.f('ix_support_queries_branch_id'), 'support_queries', ['branch_id'], unique=False)
    op.create_index(op.f('ix_support_queries_organization_id'), 'support_queries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_support_queries_resident_id'), 'support_queries', ['resident_id'], unique=False)
    op.create_index(op.f('ix_support_queries_status'), 'support_queries', ['status'], unique=False)
    op.create_table('visitors',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('resident_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('relation', sa.String(length=60), nullable=True),
    sa.Column('purpose', sa.String(length=200), nullable=True),
    sa.Column('expected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'INSIDE', 'COMPLETED', name='visitorstatus', native_enum=False, length=12), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('id_proof_reference', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resident_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitors_branch_id'), 'visitors', ['branch_id'], unique=False)
    op.create_index(op.f('ix_visitors_name'), 'visitors', ['name'], unique=False)
    op.create_index('ix_visitors_org_branch_status', 'visitors', ['organization_id', 'branch_id', 'status'], unique=False)
    op.create_index(op.f('ix_visitors_organization_id'), 'visitors', ['organization_id'], unique=False)
    op.create_index(op.f('ix_visitors_resident_id'), 'visitors', ['resident_id'], unique=False)
    op.create_index(op.f('ix_visitors_status'), 'visitors', ['status'], unique=False)
    op.create_table('gate_logs',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('resident_id', sa.UUID(), nullable=True),
    sa.Column('visitor_id', sa.UUID(), nullable=True),
    sa.Column('direction', sa.Enum('ENTRY', 'EXIT', name='gatedirection', native_enum=False, length=10), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gate', sa.String(length=60), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('recorded_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resident_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gate_logs_branch_id'), 'gate_logs', ['branch_id'], unique=False)
    op.create_index(op.f('ix_gate_logs_direction'), 'gate_logs', ['direction'], unique=False)
    op.create_index(op.f('ix_gate_logs_occurred_at'), 'gate_logs', ['occurred_at'], unique=False)
    op.create_index('ix_gate_logs_org_branch_time', 'gate_logs', ['organization_id', 'branch_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_gate_logs_organization_id'), 'gate_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_gate_logs_resident_id'), 'gate_logs', ['resident_id'], unique=False)
    op.create_index(op.f('ix_gate_logs_visitor_id'), 'gate_logs', ['visitor_id'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('txn_type', sa.Enum('STOCK_IN', 'STOCK_OUT', 'ADJUSTMENT', 'TRANSFER', name='inventorytxntype', native_enum=False, length=12), nullable=False),
    sa.Column('quantity_delta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transactions_branch_id'), 'inventory_transactions', ['branch_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_item_id'), 'inventory_transactions', ['item_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_organization_id'), 'inventory_transactions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_txn_type'), 'inventory_transactions', ['txn_type'], unique=False)
    op.create_table('invoice_items',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('RENT', 'DEPOSIT', 'FOOD', 'LAUNDRY', 'ELECTRICITY', 'MAINTENANCE', 'LATE_FEE', 'DISCOUNT', 'OTHER', name='invoiceitemkind', native_enum=False, length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_invoice_items_non_negative'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_kind'), 'invoice_items', ['kind'], unique=False)
    op.create_index(op.f('ix_invoice_items_organization_id'), 'invoice_items', ['organization_id'], unique=False)
    op.create_table('laundry_requests',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('resident_id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('BOOKED', 'RECEIVED', 'PROCESSING', 'READY', 'COLLECTED', 'CANCELLED', name='laundryrequeststatus', native_enum=False, length=12), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('item_count > 0', name='ck_laundry_item_count'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resident_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['laundry_slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resident_id', 'slot_id', name='uq_laundry_resident_slot')
    )
    op.create_index(op.f('ix_laundry_requests_branch_id'), 'laundry_requests', ['branch_id'], unique=False)
    op.create_index(op.f('ix_laundry_requests_organization_id'), 'laundry_requests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_laundry_requests_resident_id'), 'laundry_requests', ['resident_id'], unique=False)
    op.create_index(op.f('ix_laundry_requests_slot_id'), 'laundry_requests', ['slot_id'], unique=False)
    op.create_index(op.f('ix_laundry_requests_status'), 'laundry_requests', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('resident_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('payment_number', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('method', sa.Enum('CASH', 'UPI', 'BANK_TRANSFER', 'CARD', 'ONLINE', 'CHEQUE', 'ADJUSTMENT', 'OTHER', name='paymentmethod', native_enum=False, length=20), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', 'REFUNDED', name='paymentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('received_by_id', sa.UUID(), nullable=True),
    sa.Column('verified_by_id', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_payments_amount_positive'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resident_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'payment_number', name='uq_payments_org_number')
    )
    op.create_index(op.f('ix_payments_branch_id'), 'payments', ['branch_id'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_method'), 'payments', ['method'], unique=False)
    op.create_index('ix_payments_org_branch_date', 'payments', ['organization_id', 'branch_id', 'payment_date'], unique=False)
    op.create_index(op.f('ix_payments_organization_id'), 'payments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_payments_resident_id'), 'payments', ['resident_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('query_messages',
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=True),
    sa.Column('author_resident_id', sa.UUID(), nullable=True),
    sa.Column('author_name', sa.String(length=160), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_resident_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_id'], ['support_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_messages_organization_id'), 'query_messages', ['organization_id'], unique=False)
    op.create_index(op.f('ix_query_messages_query_id'), 'query_messages', ['query_id'], unique=False)
    op.create_table('assets',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('asset_code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('warranty_until', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'MAINTENANCE', 'DAMAGED', 'LOST', 'DISPOSED', name='assetstatus', native_enum=False, length=12), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'asset_code', name='uq_assets_org_code')
    )
    op.create_index(op.f('ix_assets_branch_id'), 'assets', ['branch_id'], unique=False)
    op.create_index(op.f('ix_assets_category'), 'assets', ['category'], unique=False)
    op.create_index(op.f('ix_assets_name'), 'assets', ['name'], unique=False)
    op.create_index(op.f('ix_assets_organization_id'), 'assets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    op.create_table('complaints',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('resident_id', sa.UUID(), nullable=True),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('ticket_number', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='ticketpriority', native_enum=False, length=10), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'WAITING', 'RESOLVED', 'CLOSED', 'REOPENED', name='complaintstatus', native_enum=False, length=14), nullable=False),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resident_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'ticket_number', name='uq_complaints_org_ticket')
    )
    op.create_index(op.f('ix_complaints_assigned_to_id'), 'complaints', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_complaints_branch_id'), 'complaints', ['branch_id'], unique=False)
    op.create_index(op.f('ix_complaints_category'), 'complaints', ['category'], unique=False)
    op.create_index('ix_complaints_org_branch_status', 'complaints', ['organization_id', 'branch_id', 'status'], unique=False)
    op.create_index(op.f('ix_complaints_organization_id'), 'complaints', ['organization_id'], unique=False)
    op.create_index(op.f('ix_complaints_priority'), 'complaints', ['priority'], unique=False)
    op.create_index(op.f('ix_complaints_resident_id'), 'complaints', ['resident_id'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_table('complaint_updates',
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=True),
    sa.Column('author_resident_id', sa.UUID(), nullable=True),
    sa.Column('author_name', sa.String(length=160), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status_after', sa.String(length=14), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_resident_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_updates_complaint_id'), 'complaint_updates', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_complaint_updates_organization_id'), 'complaint_updates', ['organization_id'], unique=False)
    op.add_column('customers', sa.Column('building_id', sa.UUID(), nullable=True))
    op.add_column('customers', sa.Column('floor_id', sa.UUID(), nullable=True))
    op.add_column('customers', sa.Column('room_id', sa.UUID(), nullable=True))
    op.add_column('customers', sa.Column('bed_id', sa.UUID(), nullable=True))
    op.add_column('customers', sa.Column('first_name', sa.String(length=80), nullable=True))
    op.add_column('customers', sa.Column('last_name', sa.String(length=80), nullable=True))
    op.add_column('customers', sa.Column('alternate_phone', sa.String(length=20), nullable=True))
    op.add_column('customers', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('customers', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('customers', sa.Column('address', sa.String(length=400), nullable=True))
    op.add_column('customers', sa.Column('city', sa.String(length=80), nullable=True))
    op.add_column('customers', sa.Column('state', sa.String(length=80), nullable=True))
    op.add_column('customers', sa.Column('pincode', sa.String(length=10), nullable=True))
    op.add_column('customers', sa.Column('occupation', sa.String(length=120), nullable=True))
    op.add_column('customers', sa.Column('emergency_contact_name', sa.String(length=160), nullable=True))
    op.add_column('customers', sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True))
    op.add_column('customers', sa.Column('emergency_contact_relation', sa.String(length=60), nullable=True))
    op.add_column('customers', sa.Column('expected_checkout_date', sa.Date(), nullable=True))
    op.add_column('customers', sa.Column('actual_checkout_date', sa.Date(), nullable=True))
    op.add_column('customers', sa.Column('monthly_rent', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.add_column('customers', sa.Column('security_deposit', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.add_column('customers', sa.Column('rent_due_day', sa.Integer(), nullable=False, server_default='5'))
    op.add_column('customers', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('qr_token', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_customers_bed_id'), 'customers', ['bed_id'], unique=False)
    op.create_index(op.f('ix_customers_qr_token'), 'customers', ['qr_token'], unique=True)
    op.create_index(op.f('ix_customers_room_id'), 'customers', ['room_id'], unique=False)
    op.create_foreign_key(None, 'customers', 'floors', ['floor_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'customers', 'rooms', ['room_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'customers', 'buildings', ['building_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'customers', 'beds', ['bed_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('department', sa.String(length=40), nullable=True))
    op.add_column('users', sa.Column('designation', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('emergency_contact_name', sa.String(length=160), nullable=True))
    op.add_column('users', sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_users_department'), 'users', ['department'], unique=False)
    # Backfill defaults for the columns added to the existing customers table.
    # The application always supplies these, so the defaults are dropped again
    # to keep the schema matching the models.
    for column in ("monthly_rent", "security_deposit", "rent_due_day"):
        op.alter_column("customers", column, server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_department'), table_name='users')
    op.drop_column('users', 'emergency_contact_phone')
    op.drop_column('users', 'emergency_contact_name')
    op.drop_column('users', 'designation')
    op.drop_column('users', 'department')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_room_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_qr_token'), table_name='customers')
    op.drop_index(op.f('ix_customers_bed_id'), table_name='customers')
    op.drop_column('customers', 'qr_token')
    op.drop_column('customers', 'notes')
    op.drop_column('customers', 'rent_due_day')
    op.drop_column('customers', 'security_deposit')
    op.drop_column('customers', 'monthly_rent')
    op.drop_column('customers', 'actual_checkout_date')
    op.drop_column('customers', 'expected_checkout_date')
    op.drop_column('customers', 'emergency_contact_relation')
    op.drop_column('customers', 'emergency_contact_phone')
    op.drop_column('customers', 'emergency_contact_name')
    op.drop_column('customers', 'occupation')
    op.drop_column('customers', 'pincode')
    op.drop_column('customers', 'state')
    op.drop_column('customers', 'city')
    op.drop_column('customers', 'address')
    op.drop_column('customers', 'gender')
    op.drop_column('customers', 'date_of_birth')
    op.drop_column('customers', 'alternate_phone')
    op.drop_column('customers', 'last_name')
    op.drop_column('customers', 'first_name')
    op.drop_column('customers', 'bed_id')
    op.drop_column('customers', 'room_id')
    op.drop_column('customers', 'floor_id')
    op.drop_column('customers', 'building_id')
    op.drop_index(op.f('ix_complaint_updates_organization_id'), table_name='complaint_updates')
    op.drop_index(op.f('ix_complaint_updates_complaint_id'), table_name='complaint_updates')
    op.drop_table('complaint_updates')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_resident_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_priority'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_organization_id'), table_name='complaints')
    op.drop_index('ix_complaints_org_branch_status', table_name='complaints')
    op.drop_index(op.f('ix_complaints_category'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_branch_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_assigned_to_id'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_organization_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_name'), table_name='assets')
    op.drop_index(op.f('ix_assets_category'), table_name='assets')
    op.drop_index(op.f('ix_assets_branch_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_query_messages_query_id'), table_name='query_messages')
    op.drop_index(op.f('ix_query_messages_organization_id'), table_name='query_messages')
    op.drop_table('query_messages')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_resident_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_organization_id'), table_name='payments')
    op.drop_index('ix_payments_org_branch_date', table_name='payments')
    op.drop_index(op.f('ix_payments_method'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_branch_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_laundry_requests_status'), table_name='laundry_requests')
    op.drop_index(op.f('ix_laundry_requests_slot_id'), table_name='laundry_requests')
    op.drop_index(op.f('ix_laundry_requests_resident_id'), table_name='laundry_requests')
    op.drop_index(op.f('ix_laundry_requests_organization_id'), table_name='laundry_requests')
    op.drop_index(op.f('ix_laundry_requests_branch_id'), table_name='laundry_requests')
    op.drop_table('laundry_requests')
    op.drop_index(op.f('ix_invoice_items_organization_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_kind'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_inventory_transactions_txn_type'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_organization_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_item_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_branch_id'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_gate_logs_visitor_id'), table_name='gate_logs')
    op.drop_index(op.f('ix_gate_logs_resident_id'), table_name='gate_logs')
    op.drop_index(op.f('ix_gate_logs_organization_id'), table_name='gate_logs')
    op.drop_index('ix_gate_logs_org_branch_time', table_name='gate_logs')
    op.drop_index(op.f('ix_gate_logs_occurred_at'), table_name='gate_logs')
    op.drop_index(op.f('ix_gate_logs_direction'), table_name='gate_logs')
    op.drop_index(op.f('ix_gate_logs_branch_id'), table_name='gate_logs')
    op.drop_table('gate_logs')
    op.drop_index(op.f('ix_visitors_status'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_resident_id'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_organization_id'), table_name='visitors')
    op.drop_index('ix_visitors_org_branch_status', table_name='visitors')
    op.drop_index(op.f('ix_visitors_name'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_branch_id'), table_name='visitors')
    op.drop_table('visitors')
    op.drop_index(op.f('ix_support_queries_status'), table_name='support_queries')
    op.drop_index(op.f('ix_support_queries_resident_id'), table_name='support_queries')
    op.drop_index(op.f('ix_support_queries_organization_id'), table_name='support_queries')
    op.drop_index(op.f('ix_support_queries_branch_id'), table_name='support_queries')
    op.drop_table('support_queries')
    op.drop_index(op.f('ix_resident_kyc_status'), table_name='resident_kyc')
    op.drop_index(op.f('ix_resident_kyc_resident_id'), table_name='resident_kyc')
    op.drop_index(op.f('ix_resident_kyc_organization_id'), table_name='resident_kyc')
    op.drop_table('resident_kyc')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_resident_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_resident_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_organization_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_kind'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_meal_org_branch_date', table_name='meal_attendance')
    op.drop_index(op.f('ix_meal_attendance_status'), table_name='meal_attendance')
    op.drop_index(op.f('ix_meal_attendance_resident_id'), table_name='meal_attendance')
    op.drop_index(op.f('ix_meal_attendance_organization_id'), table_name='meal_attendance')
    op.drop_index(op.f('ix_meal_attendance_on_date'), table_name='meal_attendance')
    op.drop_index(op.f('ix_meal_attendance_branch_id'), table_name='meal_attendance')
    op.drop_table('meal_attendance')
    op.drop_index(op.f('ix_laundry_slots_status'), table_name='laundry_slots')
    op.drop_index(op.f('ix_laundry_slots_organization_id'), table_name='laundry_slots')
    op.drop_index(op.f('ix_laundry_slots_on_date'), table_name='laundry_slots')
    op.drop_index(op.f('ix_laundry_slots_branch_id'), table_name='laundry_slots')
    op.drop_table('laundry_slots')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index('ix_invoices_resident_period', table_name='invoices')
    op.drop_index(op.f('ix_invoices_resident_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_period'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_organization_id'), table_name='invoices')
    op.drop_index('ix_invoices_org_branch_status', table_name='invoices')
    op.drop_index(op.f('ix_invoices_due_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_branch_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_inventory_items_organization_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_name'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_category'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_branch_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_gate_passes_status'), table_name='gate_passes')
    op.drop_index(op.f('ix_gate_passes_resident_id'), table_name='gate_passes')
    op.drop_index(op.f('ix_gate_passes_organization_id'), table_name='gate_passes')
    op.drop_index('ix_gate_passes_org_branch_status', table_name='gate_passes')
    op.drop_index(op.f('ix_gate_passes_branch_id'), table_name='gate_passes')
    op.drop_table('gate_passes')
    op.drop_index(op.f('ix_food_menus_organization_id'), table_name='food_menus')
    op.drop_index(op.f('ix_food_menus_on_date'), table_name='food_menus')
    op.drop_index(op.f('ix_food_menus_meal'), table_name='food_menus')
    op.drop_index(op.f('ix_food_menus_branch_id'), table_name='food_menus')
    op.drop_table('food_menus')
    op.drop_index(op.f('ix_expenses_spent_on'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_organization_id'), table_name='expenses')
    op.drop_index('ix_expenses_org_branch_date', table_name='expenses')
    op.drop_index(op.f('ix_expenses_category'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_branch_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_attendance_user_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_subject'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_status'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_resident_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_organization_id'), table_name='attendance')
    op.drop_index('ix_attendance_org_branch_date', table_name='attendance')
    op.drop_index(op.f('ix_attendance_on_date'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_branch_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_announcements_status'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_organization_id'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_branch_id'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_audience'), table_name='announcements')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_organization_settings_organization_id'), table_name='organization_settings')
    op.drop_table('organization_settings')
    # ### end Alembic commands ###
