"""Platform billing: wallet, coupons and Dygine Pay

Revision ID: 0019_platform_billing
Revises: 0018_notification_preference

How a PG owner pays the platform. Nothing here touches the resident rent tables
in `billing.py` - that money settles through each owner's own Razorpay keys and
is a separate system that this one must not disturb.

Written by hand rather than autogenerated. Autogenerate wanted to drop the
unique constraints on `site_blocks.key` and `site_images.slot` and rewrite a
dozen unrelated server defaults, all of it pre-existing drift between the models
and earlier migrations. A migration that quietly fixes unrelated drift is a
migration nobody can review.

Money is stored in paise as BIGINT throughout. The rest of the application uses
NUMERIC(12,2) rupees, which is right where a human types the figure; it is wrong
at a gateway boundary, where every amount crosses as an integer.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0019_platform_billing"
down_revision = "0018_notification_preference"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ---------------------------------------------------- billing profile --
    op.create_table(
        "org_billing_profiles",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("dygine_external_id", sa.String(80)),
        # Display copy of the balance Dygine holds. Never authoritative: every
        # spend goes to Dygine, which takes a row lock and decides.
        sa.Column("cached_wallet_paise", sa.BigInteger(), nullable=False,
                  server_default="0"),
        sa.Column("cached_at", sa.DateTime(timezone=True)),
        sa.Column("auto_debit_enabled", sa.Boolean(), nullable=False,
                  server_default=sa.true()),
        sa.Column("low_balance_notified_on", sa.Date()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"],
                                ondelete="CASCADE"),
        sa.UniqueConstraint("organization_id", name="uq_org_billing_profile_org"),
        sa.CheckConstraint("cached_wallet_paise >= 0",
                           name="ck_org_billing_cache_non_negative"),
    )
    op.create_index("ix_org_billing_profiles_organization_id",
                    "org_billing_profiles", ["organization_id"])

    # ---------------------------------------------------------- coupons --
    op.create_table(
        "platform_coupons",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("code", sa.String(40), nullable=False),
        sa.Column("description", sa.String(300)),
        sa.Column("kind", sa.String(10), nullable=False, server_default="percent"),
        # Whole-number percent, or paise for a fixed discount.
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("max_discount_paise", sa.BigInteger()),
        sa.Column("min_amount_paise", sa.BigInteger(), nullable=False,
                  server_default="0"),
        sa.Column("applies_to_plans", sa.JSON(), nullable=False,
                  server_default="[]"),
        sa.Column("applies_to_cycles", sa.Integer(), server_default="1"),
        sa.Column("valid_from", sa.Date()),
        sa.Column("valid_until", sa.Date()),
        sa.Column("max_redemptions", sa.Integer()),
        sa.Column("max_per_org", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("status", sa.String(12), nullable=False, server_default="active"),
        sa.Column("created_by_id", postgresql.UUID(as_uuid=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.UniqueConstraint("code", name="uq_platform_coupons_code"),
        sa.CheckConstraint("value > 0", name="ck_coupon_value_positive"),
        sa.CheckConstraint("kind IN ('percent','fixed')", name="ck_coupon_kind"),
        sa.CheckConstraint("status IN ('active','paused','expired')",
                           name="ck_coupon_status"),
        sa.CheckConstraint("max_per_org > 0", name="ck_coupon_per_org_positive"),
        # A percentage over 100 would pay the customer to subscribe.
        sa.CheckConstraint("kind <> 'percent' OR value <= 100",
                           name="ck_coupon_percent_range"),
        sa.CheckConstraint(
            "valid_until IS NULL OR valid_from IS NULL OR valid_until >= valid_from",
            name="ck_coupon_date_order"),
    )
    op.create_index("ix_platform_coupons_code", "platform_coupons", ["code"])
    op.create_index("ix_platform_coupons_status", "platform_coupons", ["status"])

    op.create_table(
        "platform_coupon_assignments",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("coupon_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("notified_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["coupon_id"], ["platform_coupons.id"],
                                ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"],
                                ondelete="CASCADE"),
        sa.UniqueConstraint("coupon_id", "organization_id",
                            name="uq_coupon_assignment"),
    )
    op.create_index("ix_coupon_assignments_coupon",
                    "platform_coupon_assignments", ["coupon_id"])
    op.create_index("ix_coupon_assignments_org",
                    "platform_coupon_assignments", ["organization_id"])

    # ------------------------------------------------------------ charges --
    # Created before redemptions: the redemption carries an FK to it.
    op.create_table(
        "platform_charges",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("plan_id", postgresql.UUID(as_uuid=True)),
        sa.Column("purpose", sa.String(20), nullable=False,
                  server_default="subscription"),
        sa.Column("method", sa.String(10), nullable=False, server_default="gateway"),
        sa.Column("period", sa.Date()),
        sa.Column("gross_paise", sa.BigInteger(), nullable=False),
        sa.Column("discount_paise", sa.BigInteger(), nullable=False,
                  server_default="0"),
        sa.Column("net_paise", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(12), nullable=False, server_default="created"),
        sa.Column("dygine_session_id", sa.String(80)),
        sa.Column("dygine_payment_ref", sa.String(80)),
        sa.Column("dygine_invoice_number", sa.String(40)),
        sa.Column("dygine_invoice_id", sa.String(80)),
        sa.Column("checkout_url", sa.Text()),
        # Stable per (org, period, purpose). Unique, so a double-clicked renew
        # button cannot open a second charge for the same month.
        sa.Column("idempotency_key", sa.String(120), nullable=False),
        sa.Column("failure_reason", sa.String(400)),
        sa.Column("paid_at", sa.DateTime(timezone=True)),
        # Set when this charge extended the subscription. The guard that stops
        # a redelivered webhook granting two months for one payment.
        sa.Column("applied_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"],
                                ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["plan_id"], ["subscription_plans.id"],
                                ondelete="SET NULL"),
        sa.UniqueConstraint("idempotency_key", name="uq_platform_charge_idem"),
        sa.CheckConstraint(
            "net_paise >= 0 AND gross_paise >= 0 AND discount_paise >= 0",
            name="ck_charge_non_negative"),
        sa.CheckConstraint("status IN ('created','paid','failed','cancelled')",
                           name="ck_charge_status"),
    )
    op.create_index("ix_platform_charges_organization_id", "platform_charges",
                    ["organization_id"])
    op.create_index("ix_platform_charges_period", "platform_charges", ["period"])
    op.create_index("ix_platform_charges_status", "platform_charges", ["status"])
    op.create_index("ix_platform_charges_payment_ref", "platform_charges",
                    ["dygine_payment_ref"])
    op.create_index("ix_charge_org_created", "platform_charges",
                    ["organization_id", "created_at"])

    op.create_table(
        "platform_coupon_redemptions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("coupon_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("period", sa.Date()),
        sa.Column("gross_paise", sa.BigInteger(), nullable=False),
        sa.Column("discount_paise", sa.BigInteger(), nullable=False),
        sa.Column("net_paise", sa.BigInteger(), nullable=False),
        # reserved -> confirmed on payment, -> released on failure or expiry.
        sa.Column("state", sa.String(12), nullable=False, server_default="reserved"),
        sa.Column("reserved_until", sa.DateTime(timezone=True)),
        sa.Column("confirmed_at", sa.DateTime(timezone=True)),
        sa.Column("released_reason", sa.String(200)),
        sa.Column("charge_id", postgresql.UUID(as_uuid=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["coupon_id"], ["platform_coupons.id"],
                                ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"],
                                ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["charge_id"], ["platform_charges.id"],
                                ondelete="SET NULL"),
        sa.CheckConstraint("state IN ('reserved','confirmed','released')",
                           name="ck_redemption_state"),
        sa.CheckConstraint("discount_paise >= 0 AND net_paise >= 0",
                           name="ck_redemption_non_negative"),
    )
    op.create_index("ix_coupon_redemptions_coupon",
                    "platform_coupon_redemptions", ["coupon_id"])
    op.create_index("ix_coupon_redemptions_org",
                    "platform_coupon_redemptions", ["organization_id"])
    op.create_index("ix_redemption_coupon_state", "platform_coupon_redemptions",
                    ["coupon_id", "state"])
    op.create_index("ix_redemption_org", "platform_coupon_redemptions",
                    ["organization_id", "state"])
    op.create_index("ix_coupon_redemptions_state", "platform_coupon_redemptions",
                    ["state"])

    # ------------------------------------------------------- inbound log --
    op.create_table(
        "dygine_events",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        # Dygine's own event id. Unique, which is what makes processing
        # idempotent: a redelivery hits this constraint and is acknowledged
        # without being applied a second time.
        sa.Column("event_id", sa.String(80), nullable=False),
        sa.Column("event_type", sa.String(60), nullable=False),
        sa.Column("signature", sa.String(128)),
        sa.Column("raw_body", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON()),
        sa.Column("processed_at", sa.DateTime(timezone=True)),
        sa.Column("process_error", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.func.now()),
        sa.UniqueConstraint("event_id", name="uq_dygine_events_event_id"),
    )
    op.create_index("ix_dygine_events_type_created", "dygine_events",
                    ["event_type", "created_at"])
    op.create_index("ix_dygine_events_event_type", "dygine_events", ["event_type"])

    # ------------------------------------------- platform settings columns --
    # Off by default. A deployment that has not configured Dygine must not
    # report a payment channel it cannot actually use.
    op.add_column("platform_settings",
                  sa.Column("dygine_enabled", sa.Boolean(), nullable=False,
                            server_default=sa.false()))
    op.add_column("platform_settings",
                  sa.Column("dygine_base_url", sa.String(200)))
    op.add_column("platform_settings", sa.Column("dygine_key_id", sa.String(80)))
    op.add_column("platform_settings",
                  sa.Column("dygine_key_secret_encrypted", sa.Text()))
    op.add_column("platform_settings",
                  sa.Column("dygine_webhook_secret_encrypted", sa.Text()))
    op.add_column("platform_settings",
                  sa.Column("dygine_verified_at", sa.DateTime(timezone=True)))
    op.add_column("platform_settings",
                  sa.Column("wallet_low_balance_warning_days", sa.Integer(),
                            nullable=False, server_default="7"))
    op.add_column("platform_settings",
                  sa.Column("wallet_topup_presets", sa.JSON(), nullable=False,
                            server_default='[1000, 5000, 10000, 25000]'))
    op.create_check_constraint(
        "ck_platform_wallet_warning_days", "platform_settings",
        "wallet_low_balance_warning_days BETWEEN 0 AND 60")


def downgrade() -> None:
    op.drop_constraint("ck_platform_wallet_warning_days", "platform_settings",
                       type_="check")
    for column in ("wallet_topup_presets", "wallet_low_balance_warning_days",
                   "dygine_verified_at", "dygine_webhook_secret_encrypted",
                   "dygine_key_secret_encrypted", "dygine_key_id",
                   "dygine_base_url", "dygine_enabled"):
        op.drop_column("platform_settings", column)

    op.drop_table("dygine_events")
    op.drop_table("platform_coupon_redemptions")
    op.drop_table("platform_charges")
    op.drop_table("platform_coupon_assignments")
    op.drop_table("platform_coupons")
    op.drop_table("org_billing_profiles")
